import { useState } from "react";
import {
  FileText,
  Download,
  Eye,
  Sparkles,
  Clock,
  CheckCircle2,
  Edit,
  History,
  AlertTriangle,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { reports } from "@/data/mockData";

const complianceRequirements = [
  { id: "cr1", name: "FITARA Scorecard Submission", status: "Compliant", dueDate: "2025-03-31", category: "IT Governance" },
  { id: "cr2", name: "FISMA Annual Report", status: "In Progress", dueDate: "2025-06-30", category: "Cybersecurity" },
  { id: "cr3", name: "OMB A-11 Budget Exhibit", status: "Compliant", dueDate: "2025-09-15", category: "Budget" },
  { id: "cr4", name: "GAO Audit Response", status: "Pending", dueDate: "2025-08-01", category: "Oversight" },
  { id: "cr5", name: "GPRA Performance Report", status: "Compliant", dueDate: "2025-02-15", category: "Performance" },
];

const auditLog = [
  { action: "Report RPT-005 draft generated by AI", user: "System", time: "2 hours ago" },
  { action: "Report RPT-004 submitted for review by Sarah Chen", user: "Sarah Chen", time: "1 day ago" },
  { action: "Compliance requirement CR-02 status updated", user: "James Rodriguez", time: "2 days ago" },
  { action: "Report RPT-003 version 1.1 saved", user: "Sarah Chen", time: "3 days ago" },
  { action: "Congressional briefing template updated", user: "System", time: "5 days ago" },
];

function getStatusBadge(status: string) {
  switch (status) {
    case "Published": return "gov-badge-success";
    case "Draft": return "gov-badge-info";
    case "Under Review": return "gov-badge-warning";
    case "AI Generating": return "gov-badge-info";
    case "Compliant": return "gov-badge-success";
    case "In Progress": return "gov-badge-info";
    case "Pending": return "gov-badge-warning";
    default: return "gov-badge-neutral";
  }
}

export default function Reporting() {
  const [generating, setGenerating] = useState(false);
  const [generatedText, setGeneratedText] = useState("");

  const handleGenerate = (type: string) => {
    setGenerating(true);
    setGeneratedText("");
    const texts: Record<string, string> = {
      "Executive Summary": "The National Infrastructure Resilience Initiative continues to execute within planned parameters during Q1 FY2025. Budget utilization stands at 46.7% ($1.12B of $2.4B), tracking slightly below planned obligations due to delayed inter-agency data sharing agreements. Phase 2 execution has achieved 62% milestone completion, with Regional Pilot Deployments progressing ahead of schedule in two of four target corridors. Key risks include a persistent cybersecurity workforce shortage and potential FY26 budget sequestration impacts. Compliance posture remains strong at 87% across all regulatory requirements.",
      "Risk Assessment": "RISK LEVEL: MODERATE\n\nCritical Risk: Cybersecurity talent gap (R1) — Only 4 of 12 Cloud Security Engineer positions filled. This creates direct dependency risk for Milestone M5 (Cybersecurity Framework Integration). Mitigation: Expanded fellowship programs and inter-agency detail assignments under consideration.\n\nElevated Risk: Budget sequestration (R2) — Medium likelihood for FY26 with high potential impact. Contingency scope reduction plan in development.\n\nEmerging Risk: Inter-agency data sharing delays (R3) — Agreement delays with DOE may impact energy grid integration timeline. Escalated to Deputy Secretary level.",
      "Budget Justification": "FY2026 BUDGET JUSTIFICATION — NIRI\n\nRequested: $580M (Operations: $340M, Personnel: $140M, Technology: $100M)\n\nJustification: Continued execution of Phase 2 regional deployments requires sustained funding levels. The requested amount reflects a 4.2% increase over FY25 to account for expanded cybersecurity workforce requirements and technology modernization costs.\n\nCost Avoidance: Ordinance AI platform has reduced PMO consulting costs by $39.5M annually (82% reduction), representing the largest single efficiency gain in program history.",
    };
    setTimeout(() => {
      setGeneratedText(texts[type] || texts["Executive Summary"]);
      setGenerating(false);
    }, 2000);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold">Oversight & Reporting Center</h1>
        <p className="text-sm text-muted-foreground mt-1">Automated compliance reporting and congressional briefing generation</p>
      </div>

      {/* AI Report Generation */}
      <Card className="border-accent/20 bg-accent/[0.02]">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-accent" />
            AI Report Generator
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex gap-2 mb-4">
            {["Executive Summary", "Risk Assessment", "Budget Justification"].map((type) => (
              <Button
                key={type}
                size="sm"
                variant="outline"
                onClick={() => handleGenerate(type)}
                disabled={generating}
                className="text-xs"
              >
                <Sparkles className="w-3 h-3 mr-1" />
                Generate {type}
              </Button>
            ))}
          </div>
          {(generating || generatedText) && (
            <div className="bg-muted/50 rounded-lg p-4 min-h-[100px]">
              {generating ? (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Sparkles className="w-4 h-4 animate-pulse text-accent" />
                  Generating report from program data...
                </div>
              ) : (
                <div className="text-xs leading-relaxed whitespace-pre-line">{generatedText}</div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Reports */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold">Report Library</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {reports.map((r) => (
              <div key={r.id} className="flex items-center gap-3 py-2 border-b last:border-0">
                <FileText className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium truncate">{r.title}</p>
                  <div className="flex items-center gap-2 mt-0.5">
                    <span className="text-[10px] text-muted-foreground">{r.date}</span>
                    <span className="text-[10px] text-muted-foreground">v{r.version}</span>
                  </div>
                </div>
                <span className={`${getStatusBadge(r.status)} text-[9px]`}>{r.status}</span>
                <div className="flex gap-1">
                  <Button variant="ghost" size="icon" className="h-6 w-6">
                    <Eye className="w-3 h-3" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-6 w-6">
                    <Download className="w-3 h-3" />
                  </Button>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        {/* Compliance */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold">Compliance Requirements</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {complianceRequirements.map((cr) => (
              <div key={cr.id} className="flex items-center gap-3 py-2 border-b last:border-0">
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium">{cr.name}</p>
                  <div className="flex items-center gap-2 mt-0.5">
                    <span className="text-[10px] text-muted-foreground">{cr.category}</span>
                    <span className="text-[10px] text-muted-foreground">Due {cr.dueDate}</span>
                  </div>
                </div>
                <span className={`${getStatusBadge(cr.status)} text-[9px]`}>{cr.status}</span>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>

      {/* Audit Trail */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <History className="w-4 h-4" />
            Audit Trail
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {auditLog.map((entry, i) => (
              <div key={i} className="flex items-center gap-3 py-1.5 border-b last:border-0">
                <Clock className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
                <p className="text-xs flex-1">{entry.action}</p>
                <span className="text-[10px] text-muted-foreground">{entry.user}</span>
                <span className="text-[10px] text-muted-foreground">{entry.time}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
